# Generated by Django 5.0.3 on 2024-03-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default=' ', max_length=70),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=' ', max_length=70),
        ),
    ]
