# Generated by Django 5.0.3 on 2024-03-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_city_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], max_length=10),
        ),
    ]
