# Generated by Django 5.0.3 on 2024-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
