# Generated by Django 5.0.3 on 2024-04-04 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activation_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 11, 16, 35, 482877, tzinfo=datetime.timezone.utc)),
        ),
    ]
