# Generated by Django 5.0.3 on 2024-04-04 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_activation_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='activation_key',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 16, 1, 7, 271696, tzinfo=datetime.timezone.utc)),
        ),
    ]
