# Generated by Django 5.0.3 on 2024-04-08 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_activation_activation_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 12, 51, 5, 174308, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
