# Generated by Django 5.0.3 on 2024-04-19 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_activation_expires_at_alter_activation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation',
            name='token',
        ),
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 8, 30, 22, 67610, tzinfo=datetime.timezone.utc)),
        ),
    ]
