# Generated by Django 5.0.3 on 2024-04-19 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_activation_token_alter_activation_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation',
            name='activation_key',
        ),
        migrations.AddField(
            model_name='activation',
            name='token',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 8, 36, 31, 412823, tzinfo=datetime.timezone.utc)),
        ),
    ]
